### ISSUE TITLE
Fix whois zombie processes

### ISSUE THREAD

**Issue by mrash** [mrash/psad#15]
The following bug report was sent to the psad mailing list from "3Turtles":

My Ubuntu servers are all currently suffering from zombie processes.  I
narrowed down the culprit to PSAD (sh <defunct>'s parent is psad).

In my psad.conf file i have the noemail configured, but emails are still
trying to send out and they are failing (i did this on purpose so my
email doesnt get spammed to death) and being sent to my root mail instead.

Any idea how i can solve this?  After a few hours i have around 35
zombie processes.

**Comment by MrDaves24** [comment]
Sorry to reopen this, but I still have zombies create in version 2.4.3 on Ubuntu 20.04.3 LTS

**Comment by Permanently** [comment]
Likewise, I also have this issue still in 2.4.6.
