### ISSUE TITLE
psad -F/psad --flush issue

### ISSUE THREAD

**Issue by vanishing** [mrash/psad#21]
Recently I ran into a rather interesting problem:
I can't seem to be able to flush the blocked IP, if I issue psad -F, the chains quickly gets flushed, however the blocked IPs immediately become blocked again. However if I were to remove status.out, then flush, the chains gets flushed and it stays clean.

I am on the latest commit of psad, and my system is:

─ »»»  sudo psad -V
[+] psad v2.4.1 by Michael Rash mbr@cipherdyne.org

─ »»»  uname -a
Linux Hao 4.0.0-pf5-hao #2 SMP Sun Jun 7 00:39:15 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux

─ »»»  lsb_release -a
LSB Version:    core-2.0-amd64:core-2.0-noarch:core-3.0-amd64:core-3.0-noarch:core-3.1-amd64:core-3.1-noarch:core-3.2-amd64:core-3.2-noarch:core-4.0-amd64:core-4.0-noarch:core-4.1-amd64:core-4.1-noarch:security-4.0-amd64:security-4.0-noarch:security-4.1-amd64:security-4.1-noarch
Distributor ID: Ubuntu
Description:    Ubuntu Wily Werewolf (development branch)
Release:        15.10
Codename:       wily

**Comment by mrash** [comment]
Thanks for the bug report - interesting behavior. I'll take an in-depth look at this as soon as I can.

**Comment by mrash** [comment]
I know this response is way late, but if you are still running psad, you may want to try the psad-2.4.4 release to see if this has been fixed.

**Comment by mrash** [comment]
I believe this has been fixed as of psad-2.4.4. Please reopen the bug if not. Thanks.
