### ISSUE TITLE
psad not working 

### ISSUE THREAD

**Issue by rexchou** [mrash/psad#25]
[+] psadwatchd (pid: 24905)  %CPU: 0.0  %MEM: 0.0
    Running since: Tue Aug 18 00:42:43 2015

[+] psad (pid: 24901)  %CPU: 0.0  %MEM: 0.2
    Running since: Tue Aug 18 00:42:43 2015
    Command line arguments: [none specified]
    Alert email address(es): root@localhost 1443213244@qq.com

[+] Version: psad v2.4.1

[+] Top 50 signature matches:
        [NONE]

[+] Top 25 attackers:
        [NONE]

[+] Top 20 scanned ports:
        [NONE]

[+] iptables log prefix counters:
        [NONE]

    Total protocol packet counters:

[+] IP Status Detail:
        [NONE]

    Total scan sources: 0
    Total scan destinations: 0

[+] These results are available in: /var/log/psad/status.out

target     prot opt source               destination         
LOG        all  --  0.0.0.0/0            0.0.0.0/0            LOG flags 0 level 4
PSAD_BLOCK_INPUT  all  --  0.0.0.0/0            0.0.0.0/0           
LOG        all  --  0.0.0.0/0            0.0.0.0/0            LOG flags 0 level 4

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         
LOG        all  --  0.0.0.0/0            0.0.0.0/0            LOG flags 0 level 4

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
PSAD_BLOCK_OUTPUT  all  --  0.0.0.0/0            0.0.0.0/0           
LOG        all  --  0.0.0.0/0            0.0.0.0/0            LOG flags 0 level 4

Chain PSAD_BLOCK_INPUT (1 references)
target     prot opt source               destination         

Chain PSAD_BLOCK_OUTPUT (1 references)
target     prot opt source               destination

**Comment by mrash** [comment]
Yikes, I'll get that fixed.

**Comment by rexchou** [comment]
Thank you for sharing!

**Comment by mrash** [comment]
I've applied a commit that may help with this problem: 08032b89

However, in general, psad should exclude the '0.0.0.0' IP for all blocking actions. Do you have an auto_dl file that applies a high danger level to the 0.0.0.0 IP or something like this? Or are you using a relatively default configuration with auto blocking enabled?

Are you able to run psad from the sources in git for testing?

**Comment by rexchou** [comment]
Thank you very much, PSAD running now.

**Comment by mrash** [comment]
Ok, closing this issue for now. If you experience any further problems please let me know.
