### ISSUE TITLE
META.yml missing

### ISSUE THREAD

**Issue by itvasile** [mrash/psad#26]
I have tried to install  psad-2.4.1 and afterwards the latest version (master). Both installs failed with the following warnings (see below):

[+] Removing /usr/lib/psad/ directory from previous psad installation.
[+] Creating /usr/lib/psad
[+] mkdir /usr/lib/psad, 755
[+] Compiling Marco d'Itri's whois client
[+] CMD: '/usr/bin/make -C deps/whois'
make: Entering directory `/root/psad-master/deps/whois'
cc   -g -O2 -MM -MG *.c > Makefile.depend
make: Leaving directory `/root/psad-master/deps/whois'
make: Entering directory `/root/psad-master/deps/whois'
cc   -g -O2 -c whois.c
cc   -g -O2 -c utils.c
cc  -o whois whois.o utils.o  
cc   -g -O2 -c mkpasswd.c
cc  -o mkpasswd mkpasswd.o utils.o -lcrypt 
make: Leaving directory `/root/psad-master/deps/whois'
[+] Copying whois binary to /usr/bin/whois_psad

[+] Installing the Unix::Syslog 1.1 perl module in /usr/lib/psad/
[+] CMD: '/usr/bin/perl Makefile.PL PREFIX=/usr/lib/psad LIB=/usr/lib/psad'
Checking if your kit is complete...
Warning: the following files are missing in your kit:
	META.yml
Please inform the author.
Writing Makefile for Unix::Syslog
[+] CMD: '/usr/bin/make'
cp Syslog.pm blib/lib/Unix/Syslog.pm
/usr/bin/perl /usr/share/perl5/ExtUtils/xsubpp  -typemap /usr/share/perl5/ExtUtils/typemap  Syslog.xs > Syslog.xsc && mv Syslog.xsc Syslog.c
gcc -c   -D_REENTRANT -D_GNU_SOURCE -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic   -DVERSION=\"1.1\" -DXS_VERSION=\"1.1\" -fPIC "-I/usr/lib64/perl5/CORE"   Syslog.c
Syslog.c: In function 'XS_Unix__Syslog_priorityname':
Syslog.c:432: warning: unused variable 'targ'
Syslog.c:431: warning: unused variable 'RETVAL'
Syslog.c:430: warning: unused variable 'p'
Syslog.c: In function 'XS_Unix__Syslog_facilityname':
Syslog.c:454: warning: unused variable 'targ'
Syslog.c:453: warning: unused variable 'RETVAL'
Syslog.c:452: warning: unused variable 'f'
Syslog.c: In function 'XS_Unix__Syslog_setlogmask':
Syslog.c:570: warning: unused variable 'targ'
Syslog.c:569: warning: unused variable 'RETVAL'

**Comment by mrash** [comment]
Thanks for catching this. Fixed in master for the next release.
