### ISSUE TITLE
Add systemd init script

### ISSUE THREAD

**Issue by mrash** [mrash/psad#27]
Add an init script for systems running systemd. This issue was reported by Robert Watson to the psad mailing list.

**Comment by rathann** [comment]
Here's a systemd unit I wrote for the Fedora package:
```
[Unit]
Description=The Port Scan Attack Detector (psad)
Documentation=man:psad(8) https://www.cipherdyne.org/psad/

[Service]
Type=forking
ExecStart=/usr/sbin/psad
ExecStop=/usr/sbin/psad --Kill
ExecReload=/usr/sbin/psad --HUP
PIDFile=/var/run/psad/psad.pid

[Install]
WantedBy=multi-user.target
```
Install it as `/usr/lib/systemd/system/psad.service`. It could be improved by adding dependencies on either firewalld or iptables services, but it's a good start.

**Comment by mrash** [comment]
An initial version was added to psad-2.4.4, and I've also added your script in 430ded8b for psad-2.4.5.

**Comment by rathann** [comment]
Excellent, thank you!
