### ISSUE TITLE
ChainMgr.pm error

### ISSUE THREAD

**Issue by HellUnit** [mrash/psad#30]
Argument "1.6.1" isn't numeric in numeric gt (>) at /usr/lib/psad/IPTables/ChainMgr.pm line 414.

This occurred with version 2.4.2, which actually reports itself as 2.4.1. It still seems to be functioning properly and I'm not sure if it is an environment issue since it hasn't been previously reported.

**Comment by mrash** [comment]
Thanks for reporting this, I'll get it fixed.

On Sat, Dec 12, 2015 at 5:38 PM, Antony Prince <notifications@github.com>
wrote:

> Argument "161" isn't numeric in numeric gt (>) at
> /usr/lib/psad/IPTables/ChainMgrpm line 414
>
> This occurred with version 242, which actually reports itself as 241 It
> still seems to be functioning properly and I'm not sure if it is an
> environment issue since it hasn't been previously reported
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mrash/psad/issues/30>.
>



-- 
Michael Rash | Founder
http://www.cipherdyne.org/
Key fingerprint = 53EA 13EA 472E 3771 894F  AC69 95D8 5D6B A742 839F
