### ISSUE TITLE
can't call method "network" on an undefined value at /usr/sbin/psad line 3746

### ISSUE THREAD

**Issue by itoffshore** [mrash/psad#32]
This is probably related to the `4.1` kernel in Alpine Linux `3.3`:

`can't call method "network" on an undefined value at /usr/sbin/psad line 3746`

setting in `/etc/psad/psad.conf`:

`ENABLE_INTF_LOCAL_NETS      N;`

fixes the error & `psad` starts.

I also noticed from `psad -A`:

```
Use of uninitialized value in subroutine entry at /usr/lib/perl5/vendor_perl/NetAddr/IP/Lite.pm line 1355.
Bad arg length for NetAddr::IP::Util::hasbits, length is 0, should be 128 at /usr/lib/perl5/vendor_perl/NetAddr/IP/Lite.pm line 1355.
```

```
root@alpine [~]# uname -a
Linux alpine 4.1.15-1-grsec #2-Alpine SMP Tue Dec 29 04:01:15 GMT 2015 x86_64 GNU/Linux
root@alpine [~]# perl -v

This is perl 5, version 22, subversion 1 (v5.22.1) built for x86_64-linux-thread-multi
```

**Comment by mrash** [comment]
I know this is a massively late response, but if you still have a system where this bug in psad is reproducible, could you send me the output of 'ifconfig -a'? (You can obfuscate the IP's, but please keep any 'strangeness' that you might see.) Thanks.

**Comment by itoffshore** [comment]
The error has disappeared - Alpine uses `perl v5.22.2` & kernel `4.4.30` now
