### ISSUE TITLE
whois.c: 3 * poor error checking ?

### ISSUE THREAD

**Issue by dcb314** [mrash/psad#35]
1.

whois.c:1159]: (style) Checking if unsigned variable 'a' is less than zero.

Source code is

```
a = strtol(s, &endptr, 10);
if (errno || a < 0 || a > 255 || *endptr != '.')
```

2.
whois.c:1164]: (style) Checking if unsigned variable 'b' is less than zero.

3.
whois.c:1169]: (style) Checking if unsigned variable 'c' is less than zero.

Duplicates.

**Comment by mrash** [comment]
Thanks for pointing this out. Those checks might be defensive in nature just in case the unsigned variables are changed to signed ones at some point. Either way, even though the checks aren't necessary, they don't harm anything. The whois client is written by Marco d'Itri if you would like to like him to change the code - see: https://github.com/rfc1036/whois
