### ISSUE TITLE
Add support to ArchLinux

### ISSUE THREAD

**Issue by lifehome** [mrash/psad#42]
#  Current situation
The [package](https://aur.archlinux.org/packages/psad/) on AUR is simply broken, the reason of death remains unknown, and no matter what modification has done to the PKGBUILD(the installation script), it fails the whole installation.

# Suggestion / Proposal
Add support to systemd, and if possible(I know it's too much to ask) fix the PKGBUILD.

I am really hoping someone could fix this, but it seems nobody cares which leads me here to report. Archlinux is good at some point, and bad at some other point. However we still have a quite active community at ArchLinux, and I don't want to give up on this distro.

**Comment by mrash** [comment]
systemd is supported in psad starting around psad-2.4.0, and there is an updated systemd init script bundled with psad as of psad-2.4.4 (and even a newer one in master - see the init-scripts/systemd/ directory. Is there something specific that doesn't appear to be working with psad.

**Comment by itoffshore** [comment]
@lifehome - you could have a look at how I build `psad` for [Alpine Linux](https://github.com/alpinelinux/aports/blob/8b7e48dcaf6a2049edeffaa957db618e923b78ab/community/psad/APKBUILD)

Alpine's `APKBUILD` is very similar to Arch's `PKGBUILD` format

**Comment by lifehome** [comment]
@itoffshore Thanks, except old binaries and some PGP signature issues with the Arch AUR package, of which it is now working fine 😆
