### ISSUE TITLE
systemd-analyze blame shows psad.service as the long pole

### ISSUE THREAD

**Issue by mikejramsey56** [mrash/psad#43]
1min 17.793s psad.service

Is this normal?

My system is a VirtualBox 5.1.18  guest running Ubuntu 16.04.2 LTS

 psad v2.2.3 by Michael Rash <mbr@cipherdyne.org>

apt-get tells me that I have the latest, psad v2.2.3-1

**Comment by mrash** [comment]
psad-2.2.3 is quite old at this point, and psad needs to be updated in the Ubuntu package repositories. I'll try to get this done through the package maintainer.

In the meantime, psad didn't get systemd support until the 2.4.0 release, and psad-2.4.4 is the current release. If you are willing to upgrade psad outside of the ubuntu package, you can just run the 'install.pl' script that is bundled with the psad sources. I'd recommend just cloning the psad git repository and installing from master.

**Comment by mikejramsey56** [comment]
I took your advice and cloned the git repo and ran 'install.pl'.  Result:
10.243s psad.service

Thank you.

**Comment by mrash** [comment]
I believe that looks normal. Closing this issue, but you can reopen it if you see other problematic behavior.
