### ISSUE TITLE
psad didn't find killall

### ISSUE THREAD

**Issue by WagnerGMD** [mrash/psad#48]
```
[+] mkdir /var/log/psad, 700
[*] Could not find killall anywhere!!!  Please edit the config section to include the path to killall. at ./install.pl line 2162.
```
Hello,

I just want to report this error (because as today, it's seem to not longer exist (under **Stretch** (aka Debian 9)).

Kind regards.

**PS :** Almost 2 weeks later. Then for the moment, one solution might be to first run this command : ` apt install psad`. Once it's done, the error might be gone and apparently it was updated (psad_v2.4.3 --->psad_v2.4.5 by the command : `./install.pl`).

**Comment by mrash** [comment]
Switched to ‘pkill' instead of using killall in git master.

**Comment by WagnerGMD** [comment]
**Damn it, finally there is one reply and that's a record "1 year and 3 months later" !** 

At least thank you @mrash because I assume the trouble has gone. But I won't able to confirm this fact.
That's right, I could be very patient (such as 3 or 6 months) but you didn't give any sign of life... That's why I don't use psad anymore and I guess I won't give another chance for a long time.

To resume, you need to improve the support. Otherwise the people will decide to abandon the patience and **the absence of answer will be recognize as a sign of disrespect.**
