### ISSUE TITLE
support ss when netstat is not installed

### ISSUE THREAD

**Issue by rathann** [mrash/psad#53]
PSAD still depends on the `netstat` command (from net-tools) and should support using `ss` (from iproute2) when net-tools is not installed.

net-tools are obsolete [since 2009](https://lists.debian.org/debian-devel/2009/03/msg00780.html) and applications should switch to iproute2. Major distributions are using iproute2 and some, including RHEL7 don't install net-tools by default anymore. See also [this LWN article](https://lwn.net/Articles/710533/).

**Comment by mrash** [comment]
Thanks for pointing this out - agreed. I'll update psad to use 'ss'.

**Comment by rathann** [comment]
Thank you. Another option is to stop using external command line tools and switch to perl modules, but I don't know which requires more work.

**Comment by mrash** [comment]
In git master psad now uses ‘ss’ by default. Thanks.

**Comment by rathann** [comment]
Cool, thank you. Looking forward to a new release.

**Comment by rathann** [comment]
This is fixed in commit f6cc7bf0a20ed8cc4f196fe6bf323e382315586c to be precise.
