### ISSUE TITLE
from header adjustment

### ISSUE THREAD

**Issue by arzakk** [mrash/psad#54]
Hello, I would like the sending profile to be different. Currently, the alerting is working fine and I'm getting the emails I want. However the from is "root <monitoring@mydomain.com>" and I want this to be "Monitoring <monitoring@mydomain.com>". I've poked around the config and found the entry to the DSHIELD_USER_MAIL, but I'm only monitoring and this did not change the email I received.

**Comment by mrash** [comment]
Check out commit 63926b6 with the new 'EMAIL_APPEND_HEADER' functionality. This will be in psad-2.4.6.
