### ISSUE TITLE
Psad not working on Debian stretch

### ISSUE THREAD

**Issue by Doemela** [mrash/psad#57]
Hai,

If I do psad -A I get this error:

> Can't call method "within" without a package or object reference at /usr/sbin/psad line 2075.

What does it mean am I missing a perl module? install is git version with `./install.pl --force-mod-install` 
In `/bin/journalctl -f -k ` I see intrusions but Psad does not read/see them, tried several option Y/N but no luck

Plz help Doemela

Perl version v5.24.1
Operating system | Debian Linux 9
Kernel and CPU | Linux 4.9.0-6-amd64 on x86_64
ip6tables v1.6.0 | iptables v1.6.0
psad v2.4.5
[install.log](https://github.com/mrash/psad/files/1808964/install.log)
[iptablesdump.txt](https://github.com/mrash/psad/files/1808968/iptablesdump.txt)
[psad-conf.txt](https://github.com/mrash/psad/files/1808974/psad-conf.txt)

**Comment by Peac** [comment]
Same problem on Ubuntu 16.04
